/**
 * 内置价目表 —— 自动生成，不要手改。
 *
 * 由 `tools/gen_pricing_table.py` 从 models.dev 快照编译而来，
 * 只保留模型原厂/官方托管方：同一个 model id 在转售渠道之间价差可达 30 倍，
 * 随手取一条会得到看着合理、实际差一个数量级的「估算」，比不估算更糟。
 *
 * 生成日期：2026-09-30
 * 收录：xai=8、openai=48、anthropic=15、google=34、deepseek=4、moonshotai=4、kimi-code-plan-global=4、kimi-code-plan-cn=0、mistral=33、poolside=3、alibaba=58、alibaba-cn=37
 * 型号数：248
 *
 * 单位：美元 / 每 100 万 token。`cacheRead`/`cacheWrite` 为 null 表示
 * 该渠道没有公布这项价格 —— 它不是 0，遇到这种型号要按「算不出来」处理。
 */

export interface BuiltinPrice {
  /** 价格来自哪家（一方 provider id）。 */
  provider: string
  /** 未命中缓存的输入 token 单价。 */
  input: number
  output: number
  cacheRead: number | null
  cacheWrite: number | null
}

export const PRICING_GENERATED_ON = '2026-09-30'

/**
 * 一方 provider 的**优先级顺序**（靠前的赢）。
 *
 * 运行时从 models.dev 刷新价目表时按这份名单筛渠道，
 * 免得 allowlist 在 Python 和 TS 里各维护一份、迟早对不上。
 */
export const FIRST_PARTY_PROVIDERS: readonly string[] = ['xai', 'openai', 'anthropic', 'google', 'deepseek', 'moonshotai', 'kimi-code-plan-global', 'kimi-code-plan-cn', 'mistral', 'poolside', 'alibaba', 'alibaba-cn']

export const BUILTIN_PRICES: Readonly<Record<string, BuiltinPrice>> = {
  'MiniMax-M2.5': { provider: 'alibaba-cn', input: 0.3, output: 1.2, cacheRead: null, cacheWrite: null },
  'MiniMax/MiniMax-M2.7': { provider: 'alibaba-cn', input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0.375 },
  'claude-fable-5': { provider: 'anthropic', input: 10.0, output: 50.0, cacheRead: 1.0, cacheWrite: 12.5 },
  'claude-fable-5-1': { provider: 'anthropic', input: 10.0, output: 50.0, cacheRead: 0.25, cacheWrite: 12.5 },
  'claude-haiku-4-5': { provider: 'anthropic', input: 1.0, output: 5.0, cacheRead: 0.1, cacheWrite: 1.25 },
  'claude-haiku-4-5-20251001': { provider: 'anthropic', input: 1.0, output: 5.0, cacheRead: 0.1, cacheWrite: 1.25 },
  'claude-opus-4-5': { provider: 'anthropic', input: 5.0, output: 25.0, cacheRead: 0.5, cacheWrite: 6.25 },
  'claude-opus-4-5-20251101': { provider: 'anthropic', input: 5.0, output: 25.0, cacheRead: 0.5, cacheWrite: 6.25 },
  'claude-opus-4-6': { provider: 'anthropic', input: 5.0, output: 25.0, cacheRead: 0.5, cacheWrite: 6.25 },
  'claude-opus-4-7': { provider: 'anthropic', input: 5.0, output: 25.0, cacheRead: 0.5, cacheWrite: 6.25 },
  'claude-opus-4-8': { provider: 'anthropic', input: 5.0, output: 25.0, cacheRead: 0.5, cacheWrite: 6.25 },
  'claude-opus-5': { provider: 'anthropic', input: 5.0, output: 25.0, cacheRead: 0.5, cacheWrite: 6.25 },
  'claude-opus-5-5': { provider: 'anthropic', input: 4.0, output: 20.0, cacheRead: 0.2, cacheWrite: 5.0 },
  'claude-sonnet-4-5': { provider: 'anthropic', input: 3.0, output: 15.0, cacheRead: 0.3, cacheWrite: 3.75 },
  'claude-sonnet-4-5-20250929': { provider: 'anthropic', input: 3.0, output: 15.0, cacheRead: 0.3, cacheWrite: 3.75 },
  'claude-sonnet-4-6': { provider: 'anthropic', input: 3.0, output: 15.0, cacheRead: 0.3, cacheWrite: 3.75 },
  'claude-sonnet-5': { provider: 'anthropic', input: 2.0, output: 10.0, cacheRead: 0.2, cacheWrite: 2.5 },
  'codestral-latest': { provider: 'mistral', input: 0.3, output: 0.9, cacheRead: null, cacheWrite: null },
  'deep-research-max-preview-04-2026': { provider: 'google', input: 2.0, output: 12.0, cacheRead: 0.2, cacheWrite: null },
  'deep-research-preview-04-2026': { provider: 'google', input: 2.0, output: 12.0, cacheRead: 0.2, cacheWrite: null },
  'deepseek-flash': { provider: 'deepseek', input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: null },
  'deepseek-r1': { provider: 'alibaba-cn', input: 0.574, output: 2.294, cacheRead: null, cacheWrite: null },
  'deepseek-r1-0528': { provider: 'alibaba-cn', input: 0.574, output: 2.294, cacheRead: null, cacheWrite: null },
  'deepseek-r1-distill-llama-70b': { provider: 'alibaba-cn', input: 0.287, output: 0.861, cacheRead: null, cacheWrite: null },
  'deepseek-r1-distill-llama-8b': { provider: 'alibaba-cn', input: 0.0, output: 0.0, cacheRead: null, cacheWrite: null },
  'deepseek-r1-distill-qwen-1-5b': { provider: 'alibaba-cn', input: 0.0, output: 0.0, cacheRead: null, cacheWrite: null },
  'deepseek-r1-distill-qwen-14b': { provider: 'alibaba-cn', input: 0.144, output: 0.431, cacheRead: null, cacheWrite: null },
  'deepseek-r1-distill-qwen-32b': { provider: 'alibaba-cn', input: 0.287, output: 0.861, cacheRead: null, cacheWrite: null },
  'deepseek-r1-distill-qwen-7b': { provider: 'alibaba-cn', input: 0.072, output: 0.144, cacheRead: null, cacheWrite: null },
  'deepseek-v3': { provider: 'alibaba-cn', input: 0.287, output: 1.147, cacheRead: null, cacheWrite: null },
  'deepseek-v3-1': { provider: 'alibaba-cn', input: 0.574, output: 1.721, cacheRead: null, cacheWrite: null },
  'deepseek-v3-2-exp': { provider: 'alibaba-cn', input: 0.287, output: 0.431, cacheRead: null, cacheWrite: null },
  'deepseek-v4-flash': { provider: 'deepseek', input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: null },
  'deepseek-v4-flash-0731': { provider: 'alibaba', input: 0.2, output: 0.4, cacheRead: 0.04, cacheWrite: null },
  'deepseek-v4-flash-vision-exp': { provider: 'deepseek', input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: null },
  'deepseek-v4-pro': { provider: 'deepseek', input: 0.435, output: 0.87, cacheRead: 0.003625, cacheWrite: null },
  'deepseek-v4.1-flash': { provider: 'alibaba-cn', input: 0.29754, output: 1.19015, cacheRead: 0.01488, cacheWrite: null },
  'devstral-2512': { provider: 'mistral', input: 0.4, output: 2.0, cacheRead: null, cacheWrite: null },
  'devstral-latest': { provider: 'mistral', input: 0.4, output: 2.0, cacheRead: null, cacheWrite: null },
  'devstral-medium-2507': { provider: 'mistral', input: 0.4, output: 2.0, cacheRead: null, cacheWrite: null },
  'devstral-medium-latest': { provider: 'mistral', input: 0.4, output: 2.0, cacheRead: null, cacheWrite: null },
  'devstral-small-2505': { provider: 'mistral', input: 0.1, output: 0.3, cacheRead: null, cacheWrite: null },
  'devstral-small-2507': { provider: 'mistral', input: 0.1, output: 0.3, cacheRead: null, cacheWrite: null },
  'gemini-2.5-computer-use-preview-10-2025': { provider: 'google', input: 1.25, output: 10.0, cacheRead: null, cacheWrite: null },
  'gemini-2.5-flash': { provider: 'google', input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: null },
  'gemini-2.5-flash-image': { provider: 'google', input: 0.3, output: 30.0, cacheRead: 0.075, cacheWrite: null },
  'gemini-2.5-flash-lite': { provider: 'google', input: 0.1, output: 0.4, cacheRead: 0.01, cacheWrite: null },
  'gemini-2.5-flash-preview-tts': { provider: 'google', input: 0.5, output: 10.0, cacheRead: null, cacheWrite: null },
  'gemini-2.5-pro': { provider: 'google', input: 1.25, output: 10.0, cacheRead: 0.125, cacheWrite: null },
  'gemini-2.5-pro-preview-tts': { provider: 'google', input: 1.0, output: 20.0, cacheRead: null, cacheWrite: null },
  'gemini-3-flash-preview': { provider: 'google', input: 0.5, output: 3.0, cacheRead: 0.05, cacheWrite: null },
  'gemini-3-pro-image': { provider: 'google', input: 2.0, output: 120.0, cacheRead: null, cacheWrite: null },
  'gemini-3-pro-image-preview': { provider: 'google', input: 2.0, output: 120.0, cacheRead: null, cacheWrite: null },
  'gemini-3.1-flash-image': { provider: 'google', input: 0.5, output: 60.0, cacheRead: null, cacheWrite: null },
  'gemini-3.1-flash-image-preview': { provider: 'google', input: 0.5, output: 60.0, cacheRead: null, cacheWrite: null },
  'gemini-3.1-flash-lite': { provider: 'google', input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: null },
  'gemini-3.1-flash-lite-image': { provider: 'google', input: 0.25, output: 30.0, cacheRead: null, cacheWrite: null },
  'gemini-3.1-flash-lite-preview': { provider: 'google', input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: null },
  'gemini-3.1-flash-live-preview': { provider: 'google', input: 0.75, output: 4.5, cacheRead: null, cacheWrite: null },
  'gemini-3.1-flash-tts-preview': { provider: 'google', input: 1.0, output: 20.0, cacheRead: null, cacheWrite: null },
  'gemini-3.1-pro-preview': { provider: 'google', input: 2.0, output: 12.0, cacheRead: 0.2, cacheWrite: null },
  'gemini-3.1-pro-preview-customtools': { provider: 'google', input: 2.0, output: 12.0, cacheRead: 0.2, cacheWrite: null },
  'gemini-3.5-flash': { provider: 'google', input: 1.5, output: 9.0, cacheRead: 0.15, cacheWrite: null },
  'gemini-3.5-flash-lite': { provider: 'google', input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: null },
  'gemini-3.5-live-translate-preview': { provider: 'google', input: 3.5, output: 21.0, cacheRead: null, cacheWrite: null },
  'gemini-3.6-flash': { provider: 'google', input: 0.75, output: 3.75, cacheRead: 0.075, cacheWrite: null },
  'gemini-3.7-flash': { provider: 'google', input: 0.75, output: 3.75, cacheRead: 0.075, cacheWrite: null },
  'gemini-3.8-flash': { provider: 'google', input: 0.75, output: 3.75, cacheRead: 0.075, cacheWrite: null },
  'gemini-embedding-001': { provider: 'google', input: 0.15, output: 0.0, cacheRead: null, cacheWrite: null },
  'gemini-embedding-2': { provider: 'google', input: 0.2, output: 0.0, cacheRead: null, cacheWrite: null },
  'gemini-flash-latest': { provider: 'google', input: 0.75, output: 3.75, cacheRead: 0.075, cacheWrite: null },
  'gemini-flash-lite-latest': { provider: 'google', input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: null },
  'gemini-omni-flash-preview': { provider: 'google', input: 1.5, output: 17.5, cacheRead: null, cacheWrite: null },
  'glm-5': { provider: 'alibaba-cn', input: 0.573, output: 2.58, cacheRead: null, cacheWrite: null },
  'glm-5.1': { provider: 'alibaba-cn', input: 0.825, output: 3.301, cacheRead: 0.17, cacheWrite: null },
  'glm-5.2': { provider: 'alibaba', input: 1.4, output: 4.4, cacheRead: 0.28, cacheWrite: 0.0 },
  'glm-5.3': { provider: 'alibaba-cn', input: 1.1, output: 3.851, cacheRead: 0.275, cacheWrite: 0.0 },
  'gpt-3.5-turbo': { provider: 'openai', input: 0.5, output: 1.5, cacheRead: 0.0, cacheWrite: null },
  'gpt-4': { provider: 'openai', input: 30.0, output: 60.0, cacheRead: null, cacheWrite: null },
  'gpt-4-turbo': { provider: 'openai', input: 10.0, output: 30.0, cacheRead: null, cacheWrite: null },
  'gpt-4.1': { provider: 'openai', input: 2.0, output: 8.0, cacheRead: 0.5, cacheWrite: null },
  'gpt-4.1-mini': { provider: 'openai', input: 0.4, output: 1.6, cacheRead: 0.1, cacheWrite: null },
  'gpt-4.1-nano': { provider: 'openai', input: 0.1, output: 0.4, cacheRead: 0.025, cacheWrite: null },
  'gpt-4o': { provider: 'openai', input: 2.5, output: 10.0, cacheRead: 1.25, cacheWrite: null },
  'gpt-4o-2024-05-13': { provider: 'openai', input: 5.0, output: 15.0, cacheRead: null, cacheWrite: null },
  'gpt-4o-2024-08-06': { provider: 'openai', input: 2.5, output: 10.0, cacheRead: 1.25, cacheWrite: null },
  'gpt-4o-2024-11-20': { provider: 'openai', input: 2.5, output: 10.0, cacheRead: 1.25, cacheWrite: null },
  'gpt-4o-mini': { provider: 'openai', input: 0.15, output: 0.6, cacheRead: 0.075, cacheWrite: null },
  'gpt-5': { provider: 'openai', input: 1.25, output: 10.0, cacheRead: 0.125, cacheWrite: null },
  'gpt-5-mini': { provider: 'openai', input: 0.25, output: 2.0, cacheRead: 0.025, cacheWrite: null },
  'gpt-5-nano': { provider: 'openai', input: 0.05, output: 0.4, cacheRead: 0.005, cacheWrite: null },
  'gpt-5-pro': { provider: 'openai', input: 15.0, output: 120.0, cacheRead: null, cacheWrite: null },
  'gpt-5.1': { provider: 'openai', input: 1.25, output: 10.0, cacheRead: 0.125, cacheWrite: null },
  'gpt-5.2': { provider: 'openai', input: 1.75, output: 14.0, cacheRead: 0.175, cacheWrite: null },
  'gpt-5.2-chat-latest': { provider: 'openai', input: 1.75, output: 14.0, cacheRead: 0.175, cacheWrite: null },
  'gpt-5.2-pro': { provider: 'openai', input: 21.0, output: 168.0, cacheRead: null, cacheWrite: null },
  'gpt-5.3-chat-latest': { provider: 'openai', input: 1.75, output: 14.0, cacheRead: 0.175, cacheWrite: null },
  'gpt-5.3-codex': { provider: 'openai', input: 1.75, output: 14.0, cacheRead: 0.175, cacheWrite: null },
  'gpt-5.3-codex-spark': { provider: 'openai', input: 1.75, output: 14.0, cacheRead: 0.175, cacheWrite: null },
  'gpt-5.4': { provider: 'openai', input: 2.5, output: 15.0, cacheRead: 0.25, cacheWrite: null },
  'gpt-5.4-mini': { provider: 'openai', input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: null },
  'gpt-5.4-nano': { provider: 'openai', input: 0.2, output: 1.25, cacheRead: 0.02, cacheWrite: null },
  'gpt-5.4-pro': { provider: 'openai', input: 30.0, output: 180.0, cacheRead: null, cacheWrite: null },
  'gpt-5.5': { provider: 'openai', input: 5.0, output: 30.0, cacheRead: 0.5, cacheWrite: null },
  'gpt-5.5-pro': { provider: 'openai', input: 30.0, output: 180.0, cacheRead: null, cacheWrite: null },
  'gpt-5.6': { provider: 'openai', input: 4.0, output: 20.0, cacheRead: 0.4, cacheWrite: 5.0 },
  'gpt-5.6-luna': { provider: 'openai', input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 },
  'gpt-5.6-sol': { provider: 'openai', input: 4.0, output: 20.0, cacheRead: 0.4, cacheWrite: 5.0 },
  'gpt-5.6-terra': { provider: 'openai', input: 2.0, output: 12.0, cacheRead: 0.2, cacheWrite: 2.5 },
  'gpt-6-astra': { provider: 'openai', input: 10.0, output: 50.0, cacheRead: 1.0, cacheWrite: 12.5 },
  'gpt-6-luna': { provider: 'openai', input: 0.1, output: 0.5, cacheRead: 0.01, cacheWrite: 0.125 },
  'gpt-6-sol': { provider: 'openai', input: 2.0, output: 10.0, cacheRead: 0.2, cacheWrite: 2.5 },
  'gpt-daybreak-blue-latest': { provider: 'openai', input: 4.0, output: 20.0, cacheRead: 0.4, cacheWrite: 5.0 },
  'gpt-daybreak-red-latest': { provider: 'openai', input: 12.5, output: 75.0, cacheRead: 1.25, cacheWrite: 15.625 },
  'gpt-image-2': { provider: 'openai', input: 5.0, output: 30.0, cacheRead: 1.25, cacheWrite: null },
  'gpt-realtime-2.1': { provider: 'openai', input: 4.0, output: 24.0, cacheRead: 0.4, cacheWrite: null },
  'grok-4.20-0309-non-reasoning': { provider: 'xai', input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: null },
  'grok-4.20-0309-reasoning': { provider: 'xai', input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: null },
  'grok-4.20-multi-agent-0309': { provider: 'xai', input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: null },
  'grok-4.3': { provider: 'xai', input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: null },
  'grok-4.5': { provider: 'xai', input: 2.0, output: 6.0, cacheRead: 0.3, cacheWrite: null },
  'grok-4.6': { provider: 'xai', input: 2.0, output: 6.0, cacheRead: 0.5, cacheWrite: null },
  'grok-4.7': { provider: 'xai', input: 2.0, output: 6.0, cacheRead: 0.5, cacheWrite: null },
  'grok-build-0.1': { provider: 'xai', input: 1.0, output: 2.0, cacheRead: 0.2, cacheWrite: null },
  'k3': { provider: 'kimi-code-plan-global', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'k3-256k': { provider: 'kimi-code-plan-global', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'kimi-for-coding': { provider: 'kimi-code-plan-global', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'kimi-for-coding-highspeed': { provider: 'kimi-code-plan-global', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'kimi-k2-thinking': { provider: 'alibaba-cn', input: 0.574, output: 2.294, cacheRead: null, cacheWrite: null },
  'kimi-k2.5': { provider: 'alibaba-cn', input: 0.574, output: 2.411, cacheRead: null, cacheWrite: null },
  'kimi-k2.6': { provider: 'moonshotai', input: 0.95, output: 4.0, cacheRead: 0.16, cacheWrite: null },
  'kimi-k2.7-code': { provider: 'moonshotai', input: 0.95, output: 4.0, cacheRead: 0.19, cacheWrite: null },
  'kimi-k2.7-code-highspeed': { provider: 'moonshotai', input: 1.9, output: 8.0, cacheRead: 0.38, cacheWrite: null },
  'kimi-k3': { provider: 'moonshotai', input: 3.0, output: 15.0, cacheRead: 0.3, cacheWrite: null },
  'kimi/kimi-k2.5': { provider: 'alibaba-cn', input: 0.6, output: 3.0, cacheRead: 0.1, cacheWrite: null },
  'labs-devstral-small-2512': { provider: 'mistral', input: 0.0, output: 0.0, cacheRead: null, cacheWrite: null },
  'lyria-3-clip-preview': { provider: 'google', input: 0.0, output: 0.0, cacheRead: null, cacheWrite: null },
  'lyria-3-pro-preview': { provider: 'google', input: 0.0, output: 0.0, cacheRead: null, cacheWrite: null },
  'magistral-medium-latest': { provider: 'mistral', input: 2.0, output: 5.0, cacheRead: null, cacheWrite: null },
  'magistral-small': { provider: 'mistral', input: 0.5, output: 1.5, cacheRead: null, cacheWrite: null },
  'ministral-3b-latest': { provider: 'mistral', input: 0.04, output: 0.04, cacheRead: null, cacheWrite: null },
  'ministral-8b-latest': { provider: 'mistral', input: 0.1, output: 0.1, cacheRead: null, cacheWrite: null },
  'mistral-embed': { provider: 'mistral', input: 0.1, output: 0.0, cacheRead: null, cacheWrite: null },
  'mistral-large-2411': { provider: 'mistral', input: 2.0, output: 6.0, cacheRead: null, cacheWrite: null },
  'mistral-large-2512': { provider: 'mistral', input: 0.5, output: 1.5, cacheRead: null, cacheWrite: null },
  'mistral-large-latest': { provider: 'mistral', input: 0.5, output: 1.5, cacheRead: null, cacheWrite: null },
  'mistral-medium-2505': { provider: 'mistral', input: 0.4, output: 2.0, cacheRead: null, cacheWrite: null },
  'mistral-medium-2508': { provider: 'mistral', input: 0.4, output: 2.0, cacheRead: null, cacheWrite: null },
  'mistral-medium-2604': { provider: 'mistral', input: 1.5, output: 7.5, cacheRead: null, cacheWrite: null },
  'mistral-medium-latest': { provider: 'mistral', input: 1.5, output: 7.5, cacheRead: null, cacheWrite: null },
  'mistral-nemo': { provider: 'mistral', input: 0.15, output: 0.15, cacheRead: null, cacheWrite: null },
  'mistral-small-2506': { provider: 'mistral', input: 0.1, output: 0.3, cacheRead: null, cacheWrite: null },
  'mistral-small-2603': { provider: 'mistral', input: 0.15, output: 0.6, cacheRead: null, cacheWrite: null },
  'mistral-small-latest': { provider: 'mistral', input: 0.15, output: 0.6, cacheRead: null, cacheWrite: null },
  'moonshot-kimi-k2-instruct': { provider: 'alibaba-cn', input: 0.574, output: 2.294, cacheRead: null, cacheWrite: null },
  'o1': { provider: 'openai', input: 15.0, output: 60.0, cacheRead: 7.5, cacheWrite: null },
  'o1-pro': { provider: 'openai', input: 150.0, output: 600.0, cacheRead: null, cacheWrite: null },
  'o3': { provider: 'openai', input: 2.0, output: 8.0, cacheRead: 0.5, cacheWrite: null },
  'o3-mini': { provider: 'openai', input: 1.1, output: 4.4, cacheRead: 0.55, cacheWrite: null },
  'o3-pro': { provider: 'openai', input: 20.0, output: 80.0, cacheRead: null, cacheWrite: null },
  'o4-mini': { provider: 'openai', input: 1.1, output: 4.4, cacheRead: 0.275, cacheWrite: null },
  'open-mistral-7b': { provider: 'mistral', input: 0.25, output: 0.25, cacheRead: null, cacheWrite: null },
  'open-mistral-nemo': { provider: 'mistral', input: 0.15, output: 0.15, cacheRead: null, cacheWrite: null },
  'open-mixtral-8x22b': { provider: 'mistral', input: 2.0, output: 6.0, cacheRead: null, cacheWrite: null },
  'open-mixtral-8x7b': { provider: 'mistral', input: 0.7, output: 0.7, cacheRead: null, cacheWrite: null },
  'pixtral-12b': { provider: 'mistral', input: 0.15, output: 0.15, cacheRead: null, cacheWrite: null },
  'pixtral-large-latest': { provider: 'mistral', input: 2.0, output: 6.0, cacheRead: null, cacheWrite: null },
  'poolside/laguna-m.1': { provider: 'poolside', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'poolside/laguna-s-2.1': { provider: 'poolside', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'poolside/laguna-xs-2.1': { provider: 'poolside', input: 0.0, output: 0.0, cacheRead: 0.0, cacheWrite: 0.0 },
  'qvq-max': { provider: 'alibaba', input: 1.2, output: 4.8, cacheRead: null, cacheWrite: null },
  'qwen-deep-research': { provider: 'alibaba-cn', input: 7.742, output: 23.367, cacheRead: null, cacheWrite: null },
  'qwen-doc-turbo': { provider: 'alibaba-cn', input: 0.087, output: 0.144, cacheRead: null, cacheWrite: null },
  'qwen-flash': { provider: 'alibaba', input: 0.05, output: 0.4, cacheRead: null, cacheWrite: null },
  'qwen-long': { provider: 'alibaba-cn', input: 0.072, output: 0.287, cacheRead: null, cacheWrite: null },
  'qwen-math-plus': { provider: 'alibaba-cn', input: 0.574, output: 1.721, cacheRead: null, cacheWrite: null },
  'qwen-math-turbo': { provider: 'alibaba-cn', input: 0.287, output: 0.861, cacheRead: null, cacheWrite: null },
  'qwen-max': { provider: 'alibaba', input: 1.6, output: 6.4, cacheRead: null, cacheWrite: null },
  'qwen-mt-plus': { provider: 'alibaba', input: 2.46, output: 7.37, cacheRead: null, cacheWrite: null },
  'qwen-mt-turbo': { provider: 'alibaba', input: 0.16, output: 0.49, cacheRead: null, cacheWrite: null },
  'qwen-omni-turbo': { provider: 'alibaba', input: 0.07, output: 0.27, cacheRead: null, cacheWrite: null },
  'qwen-omni-turbo-realtime': { provider: 'alibaba', input: 0.27, output: 1.07, cacheRead: null, cacheWrite: null },
  'qwen-plus': { provider: 'alibaba', input: 0.4, output: 1.2, cacheRead: null, cacheWrite: null },
  'qwen-plus-character': { provider: 'alibaba-cn', input: 0.115, output: 0.287, cacheRead: null, cacheWrite: null },
  'qwen-plus-character-ja': { provider: 'alibaba', input: 0.5, output: 1.4, cacheRead: null, cacheWrite: null },
  'qwen-turbo': { provider: 'alibaba', input: 0.05, output: 0.2, cacheRead: null, cacheWrite: null },
  'qwen-vl-max': { provider: 'alibaba', input: 0.8, output: 3.2, cacheRead: null, cacheWrite: null },
  'qwen-vl-ocr': { provider: 'alibaba', input: 0.72, output: 0.72, cacheRead: null, cacheWrite: null },
  'qwen-vl-plus': { provider: 'alibaba', input: 0.21, output: 0.63, cacheRead: null, cacheWrite: null },
  'qwen2-5-14b-instruct': { provider: 'alibaba', input: 0.35, output: 1.4, cacheRead: null, cacheWrite: null },
  'qwen2-5-32b-instruct': { provider: 'alibaba', input: 0.7, output: 2.8, cacheRead: null, cacheWrite: null },
  'qwen2-5-72b-instruct': { provider: 'alibaba', input: 1.4, output: 5.6, cacheRead: null, cacheWrite: null },
  'qwen2-5-7b-instruct': { provider: 'alibaba', input: 0.175, output: 0.7, cacheRead: null, cacheWrite: null },
  'qwen2-5-coder-32b-instruct': { provider: 'alibaba-cn', input: 0.287, output: 0.861, cacheRead: null, cacheWrite: null },
  'qwen2-5-coder-7b-instruct': { provider: 'alibaba-cn', input: 0.144, output: 0.287, cacheRead: null, cacheWrite: null },
  'qwen2-5-math-72b-instruct': { provider: 'alibaba-cn', input: 0.574, output: 1.721, cacheRead: null, cacheWrite: null },
  'qwen2-5-math-7b-instruct': { provider: 'alibaba-cn', input: 0.144, output: 0.287, cacheRead: null, cacheWrite: null },
  'qwen2-5-omni-7b': { provider: 'alibaba', input: 0.1, output: 0.4, cacheRead: null, cacheWrite: null },
  'qwen2-5-vl-72b-instruct': { provider: 'alibaba', input: 2.8, output: 8.4, cacheRead: null, cacheWrite: null },
  'qwen2-5-vl-7b-instruct': { provider: 'alibaba', input: 0.35, output: 1.05, cacheRead: null, cacheWrite: null },
  'qwen3-14b': { provider: 'alibaba', input: 0.35, output: 1.4, cacheRead: null, cacheWrite: null },
  'qwen3-235b-a22b': { provider: 'alibaba', input: 0.7, output: 2.8, cacheRead: null, cacheWrite: null },
  'qwen3-32b': { provider: 'alibaba', input: 0.7, output: 2.8, cacheRead: null, cacheWrite: null },
  'qwen3-8b': { provider: 'alibaba', input: 0.18, output: 0.7, cacheRead: null, cacheWrite: null },
  'qwen3-asr-flash': { provider: 'alibaba', input: 0.035, output: 0.035, cacheRead: null, cacheWrite: null },
  'qwen3-coder-30b-a3b-instruct': { provider: 'alibaba', input: 0.45, output: 2.25, cacheRead: null, cacheWrite: null },
  'qwen3-coder-480b-a35b-instruct': { provider: 'alibaba', input: 1.5, output: 7.5, cacheRead: null, cacheWrite: null },
  'qwen3-coder-flash': { provider: 'alibaba', input: 0.3, output: 1.5, cacheRead: null, cacheWrite: null },
  'qwen3-coder-plus': { provider: 'alibaba', input: 1.0, output: 5.0, cacheRead: null, cacheWrite: null },
  'qwen3-livetranslate-flash-realtime': { provider: 'alibaba', input: 10.0, output: 10.0, cacheRead: null, cacheWrite: null },
  'qwen3-max': { provider: 'alibaba', input: 1.2, output: 6.0, cacheRead: null, cacheWrite: null },
  'qwen3-next-80b-a3b-instruct': { provider: 'alibaba', input: 0.5, output: 2.0, cacheRead: null, cacheWrite: null },
  'qwen3-next-80b-a3b-thinking': { provider: 'alibaba', input: 0.5, output: 6.0, cacheRead: null, cacheWrite: null },
  'qwen3-omni-flash': { provider: 'alibaba', input: 0.43, output: 1.66, cacheRead: null, cacheWrite: null },
  'qwen3-omni-flash-realtime': { provider: 'alibaba', input: 0.52, output: 1.99, cacheRead: null, cacheWrite: null },
  'qwen3-vl-235b-a22b': { provider: 'alibaba', input: 0.7, output: 2.8, cacheRead: null, cacheWrite: null },
  'qwen3-vl-30b-a3b': { provider: 'alibaba', input: 0.2, output: 0.8, cacheRead: null, cacheWrite: null },
  'qwen3-vl-plus': { provider: 'alibaba', input: 0.2, output: 1.6, cacheRead: null, cacheWrite: null },
  'qwen3.5-122b-a10b': { provider: 'alibaba', input: 0.4, output: 3.2, cacheRead: null, cacheWrite: null },
  'qwen3.5-27b': { provider: 'alibaba', input: 0.3, output: 2.4, cacheRead: null, cacheWrite: null },
  'qwen3.5-35b-a3b': { provider: 'alibaba', input: 0.25, output: 2.0, cacheRead: null, cacheWrite: null },
  'qwen3.5-397b-a17b': { provider: 'alibaba', input: 0.6, output: 3.6, cacheRead: null, cacheWrite: null },
  'qwen3.5-flash': { provider: 'alibaba', input: 0.1, output: 0.4, cacheRead: 0.01, cacheWrite: 0.125 },
  'qwen3.5-plus': { provider: 'alibaba', input: 0.4, output: 2.4, cacheRead: null, cacheWrite: null },
  'qwen3.6-27b': { provider: 'alibaba', input: 0.6, output: 3.6, cacheRead: null, cacheWrite: null },
  'qwen3.6-35b-a3b': { provider: 'alibaba', input: 0.248, output: 1.485, cacheRead: null, cacheWrite: null },
  'qwen3.6-flash': { provider: 'alibaba', input: 0.1875, output: 1.125, cacheRead: null, cacheWrite: 0.234375 },
  'qwen3.6-max-preview': { provider: 'alibaba', input: 1.3, output: 7.8, cacheRead: 0.13, cacheWrite: 1.625 },
  'qwen3.6-plus': { provider: 'alibaba', input: 0.5, output: 3.0, cacheRead: 0.05, cacheWrite: 0.625 },
  'qwen3.7-flash': { provider: 'alibaba', input: 0.03, output: 0.13, cacheRead: 0.003, cacheWrite: 0.0375 },
  'qwen3.7-max': { provider: 'alibaba', input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.125 },
  'qwen3.7-plus': { provider: 'alibaba', input: 0.4, output: 1.6, cacheRead: 0.04, cacheWrite: 0.5 },
  'qwen3.8-flash': { provider: 'alibaba', input: 0.15, output: 0.47, cacheRead: 0.016, cacheWrite: 0.2 },
  'qwen3.8-max': { provider: 'alibaba', input: 2.0, output: 6.0, cacheRead: 0.25, cacheWrite: 2.5 },
  'qwen3.8-omni-flash': { provider: 'alibaba', input: 0.15, output: 0.47, cacheRead: 0.016, cacheWrite: null },
  'qwq-32b': { provider: 'alibaba-cn', input: 0.287, output: 0.861, cacheRead: null, cacheWrite: null },
  'qwq-plus': { provider: 'alibaba', input: 0.8, output: 2.4, cacheRead: null, cacheWrite: null },
  'siliconflow/deepseek-r1-0528': { provider: 'alibaba-cn', input: 0.5, output: 2.18, cacheRead: null, cacheWrite: null },
  'siliconflow/deepseek-v3-0324': { provider: 'alibaba-cn', input: 0.25, output: 1.0, cacheRead: null, cacheWrite: null },
  'siliconflow/deepseek-v3.1-terminus': { provider: 'alibaba-cn', input: 0.27, output: 1.0, cacheRead: null, cacheWrite: null },
  'siliconflow/deepseek-v3.2': { provider: 'alibaba-cn', input: 0.27, output: 0.42, cacheRead: null, cacheWrite: null },
  'text-embedding-3-large': { provider: 'openai', input: 0.13, output: 0.0, cacheRead: null, cacheWrite: null },
  'text-embedding-3-small': { provider: 'openai', input: 0.02, output: 0.0, cacheRead: null, cacheWrite: null },
  'text-embedding-ada-002': { provider: 'openai', input: 0.1, output: 0.0, cacheRead: null, cacheWrite: null },
  'tongyi-intent-detect-v3': { provider: 'alibaba-cn', input: 0.058, output: 0.144, cacheRead: null, cacheWrite: null },
  'voxtral-small-latest': { provider: 'mistral', input: 0.1, output: 0.3, cacheRead: null, cacheWrite: null },
  'zai-glm-5-2': { provider: 'mistral', input: 1.4, output: 4.4, cacheRead: 0.14, cacheWrite: null },
  'zai-glm-5-3': { provider: 'mistral', input: 1.4, output: 4.4, cacheRead: 0.14, cacheWrite: null },
}
